### ISSUE TITLE
Log record "extra" fields are missing when using LogstashFormatter

### ISSUE THREAD

**Issue by droriv** [eht16/python-logstash-async#69] opened 2021-11-01 14:00 UTC
When using LogstashFormatter the specific log record "extra" is missing from the formatted message

```python
from loguru import logger
from logstash_async.handler import AsynchronousLogstashHandler
from logstash_async.formatter import LogstashFormatter

logstash_handler = AsynchronousLogstashHandler(
    remote_host,
    remote_port,
    database_path,
)

logstash_formatter = LogstashFormatter(
    extra={
        'default': 'extra',
    },
)

logstash_handler.setFormatter(logstash_formatter)
logger.add(
    logstash_handler,
    level=level,
    format='{message}',
    backtrace=False,
)

logger.info('some message', extra={'some': 'extra'})

```
formatted message won't include the `extra={'some': 'extra'}` but will include  `'default': 'extra'`
This is because of the `_get_extra_fields` method which doesn't add the `record.extra` to the extra fields.
solved it locally by overriding the `_get_extra_fields` locally 

```python
class MyFormatter(LogstashFormatter):
    def _get_extra_fields(self, record):
        extra_fields = super()._get_extra_fields(record=record, )

        if record.extra:
            extra_fields = record.extra | extra_fields
        return extra_fields
```

thought you might want to add this to the code as well

thanks!

**Comment by eht16** [comment] 2022-01-08 11:03
Sorry for the late response.

I can't reproduce the described behavior with your example. It results in a message like (stripped unrelated fields for readability):
```json
{
    "message": "some message.",
    "type": "python-logstash",
    "extra": {
        "some": "extra",
        "default": "extra",
    }
}
```

Which version of the library are you using?

**Comment by droriv** [comment] 2022-01-09 14:19
I'm using `python-logstash-async==2.3.0`

**Comment by eht16** [comment] 2022-01-09 15:12
I just tried with your code again, except that I replaced the logger with a standard Python logger instance and added the handler via `logger.addHandler(logstash_handler)` and got the expected result.

Might the `loguru` package related? I don't what it does.

**Comment by droriv** [comment] 2022-01-12 09:38
It might be related to loguru but as I mentioned I was able to track the problem, it's related to the `_get_extra_fields` method and after overriding it with the fix, the issue was resolved, is it ok if I'll open a pr for that fix?

**Comment by eht16** [comment] 2022-01-13 22:19
Basically a PR is ok but I would like to understand what's the difference and why it works for me with your example and why not for you.

**Comment by eht16** [comment] 2023-07-30 13:19
Feel free to open a PR if you are still interested in and re-open this one. Until then, I like to close this issue.

**Closed by eht16** 2023-07-30 13:19 UTC
