### ISSUE TITLE
JSON Parse Failure on host Field (could not set field 'ip' on object)

### ISSUE THREAD

**Issue by andriilahuta** [eht16/python-logstash-async#90] opened 2023-11-09 15:13 UTC
Due to the conflict with ECS spec, the messages can't be properly parsed in newer logstash versions.
Here's more info in a similar issue: vklochan/python-logstash#106

**Comment by eht16** [comment] 2023-12-20 12:11
Yes, the formatter classes do not support the ECS spec.
There are a few options:
- disable the ECS validation on Logstash (see the documentation for setting `pipeline.ecs_compatibility` and adjust your index pattern accordingly
- override the formatter class to pass the Logstash event as it is expected

I'd happily accept a new formatter class which is compatible with the ECS spec but I won't work on this myself.

**Comment by eht16** [comment] 2023-12-20 12:14
This is a duplicate of #39.

See also my comment https://github.com/eht16/python-logstash-async/issues/39#issuecomment-489462839 about using a `mutate` filter in Logstash to modify the event.

**Closed by eht16** 2023-12-20 12:14 UTC
Labels: enhancement, ecs
